# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    rate_limiter:
        convert_api:
            policy: 'sliding_window'
            limit: '%env(int:APP_CONVERT_RATE_LIMIT)%'
            interval: '1 minute'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
